name: testing

on: [push, pull_request]

jobs:
    build:
      runs-on: ubuntu-16.04
      strategy:
        matrix:
          ruby: [ '2.5', '2.6' ]
      name: Ruby ${{ matrix.ruby }} sample
      steps:
        - name: chechout
          uses: actions/checkout@v2
        - name: setup
          uses: actions/setup-ruby@v1
          with:
            ruby-version: ${{ matrix.ruby }}
        - run: ruby practice.rb

